language: node_js
node_js:
  - 12
dist: bionic # needs Ubuntu Bionic
sudo: required
addons:
  chrome: latest 
  firefox: latest
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - ./custom-lint.sh
  - yarn lint
  - yarn gulp
  - yarn test:chrome
  # - yarn test:firefox
